//////////////////////////////////////////////
/////////////////Question/////////////////////

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

//////////////////////////////////////////////

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

char findTheDifference(char *s, char *t)
{
    uint8_t xor = 0;
    while (*s)
        xor ^= *s++;
    while (*t)
        xor ^= *t++;
    return xor;
}
int main()
{
    char s[] = "abcd";
    char t[] = "abcde";
    printf("ans :  %c \n", findTheDifference(s, t));
    return 0;
}
